# checkout phase
FROM node:18-slim as checkout

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY package.json ./
COPY package-lock.json ./

RUN npm install --silent

COPY . ./

RUN npm run build

# build phase
FROM nginx:alpine as release

WORKDIR /app

COPY --from=checkout /app/build /usr/share/nginx/html

ENV PORT 80
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
