FROM node:18-slim as checkout

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY package.json ./
COPY package-lock.json ./

RUN npm install --silent

EXPOSE 3000

COPY . ./

CMD ["npm", "start"]