version: "3"

services:
    nginx-test:
        container_name: styl-nginx-test
        platform: "linux/amd64"
        restart: always
        working_dir: /app
        expose:
            - "80"
        ports:
            - 80:80
            - 443:443
        environment:
            PORT: 80
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/log:/var/log/nginx

            # certbot volumes
            - /etc/letsencrypt:/etc/letsencrypt
            - /var/lib/letsencrypt:/var/lib/letsencrypt/ # /var/lib/letsencrypt 는 certbot의 webroot
        build:
            context: ./client
            dockerfile: Dockerfile.prod
