version: "3.1"

services:
    client:
        image: nginx:latest
        container_name: styl-front
        platform: "linux/amd64"
        working_dir: /app
        expose:
            - "3000"
        ports:
            - "3000:80"
        environment:
            PORT: 3000
        volumes:
            - ./client/build:/usr/share/nginx/html:consistent
        depends_on:
            - app
    app:
        container_name: styl-app
        platform: "linux/amd64"
        working_dir: /app
        expose:
            - "8000"
        ports:
            - "8000:8000"
        environment:
            PORT: 8000
        volumes:
            - .:/app:consistent
        build:
            context: .
            dockerfile: Dockerfile
        command:
            [
                "uvicorn",
                "src.main:app",
                "--host",
                "0.0.0.0",
                "--port",
                "8000",
                "--reload",
            ]
        depends_on:
            psql:
                condition: service_healthy
    psql:
        image: postgres:latest
        container_name: postgres
        # restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "password"
            PGDATA: /data/postgres
        volumes:
            - ./db/:/data/postgres
            - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 1s
            timeout: 5s
            retries: 5
# version: "3"

# services:
#     app:
#         # meta data
#         container_name: styl-app
#         platform: "linux/amd64"
#         working_dir: /app
#         # port forwarding
#         expose:
#             - "8000"
#         ports:
#             - "8000:8000"
#         environment:
#             PORT: 8000
#         # volumes
#         volumes:
#             - .:/app:consistent
#         # containre
#         build:
#             context: .
#             dockerfile: Dockerfile
#         command: [
#                 "uvicorn",
#                 "src.main:app",
#                 "--host",
#                 "0.0.0.0",
#                 "--port",
#                 "8000",
#                 "--reload", # this for hot-reload in dev
#             ] # override Dockerfile CMD
#         depends_on:
#             - psql
#     psql:
#             image: postgres:latest
#             container_name: postgres
#             restart: always
#             ports:
#                 - "5432:5432"
#             environment:
#                 POSTGRES_USER: "postgres"
#                 POSTGRES_PASSWORD: "password"
#                 PGDATA: /data/postgres
#             volumes:
#                 - ./db/:/data/postgres
#                 - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
