version: "3"

services:
    app:
        # meta data
        container_name: styl-app
        platform: "linux/amd64"
        working_dir: /app
        # port forwarding
        expose:
            - "8000"
        ports:
            - "8000:8000"
        environment:
            PORT: 8000
        # volumes
        volumes:
            - .:/app:consistent
        # containre
        build:
            context: .
            dockerfile: Dockerfile
        command: [
                "uvicorn",
                "src.main:app",
                "--host",
                "0.0.0.0",
                "--port",
                "8000",
            ] # override Dockerfile CMD
    psql:
        image: postgres:latest
        container_name: postgres
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "password"
            PGDATA: /data/postgres
        volumes:
            - ./db/:/data/postgres
            - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
